Delete Row Functionality
ilai-deutel/kibi pull request #114
Opened 2021-09-22 04:41 UTC by imreyesjorge

While using this cool code editor I missed one of my favorite things in VIM, removing entire rows at once.

Hope you find this useful 😄

2021-09-27 04:39 UTC, ilai-deutel commented
Hi Jorge, thank you for your contribution!

Unfortunately, [the total line of code count for the project increases to 1027 with this PR](https://app.travis-ci.com/github/ilai-deutel/kibi/jobs/538813484), which is slightly above the limit (1024). 

Could you try trimming it down? You may be able to reuse self.delete_char() in your function: I think that deleting a row is equivalent to clearing the row, then pressing "backspace"

2021-10-04 23:26 UTC, imreyesjorge commented
I trimmed down my function a little bit, now it has fewer lines and completely deletes the line.

2021-10-05 01:22 UTC, ilai-deutel requested changes
Thanks for the changes!

2021-10-05 01:22 UTC, ilai-deutel commented on src/editor.rs~
> +#![allow(clippy::wildcard_imports)]
Please remove this file

2021-10-05 01:22 UTC, ilai-deutel commented on src/editor.rs
> +            self.delete_char();
It looks like the first row is not removed when running the command.

Before:
```
1 │a
2 │b
3 │c
~ │
```

After:
```
1 │
2 │b
3 │c
~ │
```

What do you think of adding `self.cursor.y += 1;` before `self.delete_char();`? I think that would solve the problem

2021-10-05 06:44 UTC, imreyesjorge commented
Deleted the file and made the change

2021-10-05 06:56 UTC, ilai-deutel approved these changes

2021-10-05 06:59 UTC, ilai-deutel commented
@all-contributors please add @imreyesjorge for code

2021-10-05 06:59 UTC, merged